### ISSUE TITLE
CRUD_TeamProject 시작(5.1)

### ISSUE THREAD

**Issue by hasung98** [hasung98/2021OSSL_Team3#1]
안녕하세요 윤하성입니다

**Comment by hasung98** [comment]
저는 주제를 생각해본게 
1.  캘린더 프로그램  (어떤 일정, 행사가 있는지 CRUD) 
2. 학생 관리프로그램 (이름,성별,학번,전공,성적 등)
정도 생각해봤습니다. 다른 생각 공유해주세요 ^^

**Comment by hasung98** [comment]
캘린더 프로그램으로 한다면 
1. 일정 추가 
2. 일정 삭제 
3. 일정 수정 
4. 전체 일정 출력 (read&list) 2개 
5. 파일 저장 
6. 파일 불러오기 
7. 해당 요일로 일정 찾기
8. 해달 월로 일정 찾기 
9. 달력 출력 함수

**Comment by hasung98** [comment]
이정도가 좋을 것 같아요 ^^

**Comment by sungyi98** [comment]
안녕하세요 윤성이입니다

**Comment by sungyi98** [comment]
D-day 검색 기능도 추가하면 좋을것 같아요

**Comment by sungyi98** [comment]
시험이나 과제일정, 약속일정을 관리할 수 있는 학생용 캘린더 프로그램으로 하는것도 좋을것 같아요 ^^

**Comment by sungyi98** [comment]
structure에 들어갈 내용은, 
int year
int month
int day
char type[100] 
char subject[100]

**Comment by sungyi98** [comment]
type: 과제, 시험, 팀플

**Comment by sungyi98** [comment]
5. 일정찾기 
   1) 월로 일정찾기 -> 월 입력받아서 해당 월에 일정 모두 보여줌
   2) 월&일로 일정찾기 -> 월과 일 입력받아 해당 날짜의 일정 보여줌(없으면 "일정없음")
   3) 카테고리로 일정찾기 -> 카테고리 선택(1. 과제, 2. 시험, 3. 팀플) -> 해당 카테고리의 일정 모두 보여줌


6. 달력보기 -> 년/월 입력받아서 해당하는 달력 출력

**Comment by hasung98** [comment]
typedef struct{
  int year; //년
  int month;//월
  int day;//일
  char type[100] // 과제 or 시험  or 팀프로젝트
  char text[100] //  과목 
} Calender;

int selectMenu();
int loadFile(Calender *s); //파일 불러오기
void saveData(Calender *s, int index); //파일 저장하기

int createCalender(Calender *s); 
void readCalender(Calender *s); 
void updateCalender(Calender *s); 
void deleteCalender(Calender *s);

**Comment by hasung98** [comment]
int selectDataNo(Calender *s, int count);
void searchCalender(Calender *s, int count);

**Comment by hasung98** [comment]
void listCalender(Calender *s, int count);

**Comment by hasung98** [comment]
void searchCalender_category(Calender *s, int count);
void searchCalender_month(Calender *s, int count);

**Comment by hasung98** [comment]
void showCalender();

**Comment by hasung98** [comment]
typedef struct{
  int year; //년
  int month;//월
  int day;//일
  char type[100] // 과제 or 시험 or 팀프로젝트
  char text[100] // 과목
} Calender;

int selectMenu();
int loadFile(Calender *s); //파일 불러오기
void loadData(Calender *s, int index); //파일 저장하기

int createCalender(Calender *s);
void readCalender(Calender *s);
void updateCalender(Calender *s);
void deleteCalender(Calender *s);

int selectDataNo(Calender *s, int count);
void listCalender(Calender *s, int count);

void searchCalender_category(Calender *s, int count);
void searchCalender_month(Calender *s, int count);

void showCalender();
