### ISSUE TITLE
5.8 Wiki & 함수보완

### ISSUE THREAD

**Issue by sungyi98** [hasung98/2021OSSL_Team3#11]

**Comment by sungyi98** [comment]
type = 4 "기타" 로 분류 추가하였습니다
일정 추가시 비고를 입력할지 묻는 문항을 추가하여, 입력하겠다고 하면 p->text로 비고 내용을 함께 저장하고, 이외에는 p->text == "-"로 저장합니다

**Comment by sungyi98** [comment]
월은 0<month<=12
일은 0<day<=31
type은 1,2,3,4만 입력받을 수 있도록 범위제한 하였습니다
이외의 값 입력시 "잘못 입력하였습니다"가 출력됩니다

**Comment by sungyi98** [comment]
검색 기능에서도 월과 일, type범위를 제한하였고,
검색시 검색중인 항목이 표시되도록 하였습니다.

**Comment by hasung98** [comment]
감사합니다 달력 출력함수에서도 월과 일의 범위를 제한해서 수정하겠습니다

**Comment by sungyi98** [comment]
감사합니다!!

**Comment by sungyi98** [comment]
![image](https://user-images.githubusercontent.com/70621926/117542431-94ca6b80-b053-11eb-98c8-7b630237867e.png)

이미지 업로드 test입니다

**Comment by sungyi98** [comment]
screenshots/functions.md 파일에 이미지 업로드 하는 방법:
- 원하는 이미지를 ctrl+c
- issue에 ctrl+v
- 생성된 링크를 복사하여 .md 파일에 붙여넣기

**Comment by sungyi98** [comment]
이미지와 문자를 함께 사용하는 md파일에서 개행을 하려고 할 때, 이미지가 인식이 안되거나 개행이 제대로 안되는 문제가 발생하였습니다.
제가 찾은 방법으로는, 개행하고자 하는 부분의 마지막 문장 뒤에 2~3개의 공백을 넣어주고, enter를 쳐준 후 , 다음줄에 <_br /_> 를 입력하고, 그 다음줄을 비워두고 그 다음줄에 문장을 입력하는 방법입니다. (이탤릭체가 아닌, 일반 문자로 입력하셔야 합니다)
이 방법으로 하면 이미지 파일도 깨지지 않고, 개행도 잘 되어서 혹시나 해서 공유합니다!
정석대로의 방법은 아니고, 제가 이것저것 해보면서 알게 된 방법이니 , 더 좋은 방법 있으시면 공유해주세요!

ex) 
문장
이미지 링크(공백2~3개)

<_br /_>

문장

---------------------
추가적으로, 이미지 링크를 두개 연속해서 올리면, 두 이미지가 옆으로 나란히 나오는 경우가 있었는데 이 경우에는
<이미지링크>(공백2~3개)
<이미지링크>

위와같이 하면 두개가 위아래로 나타나더라구요!
참고하세요:)

**Comment by hasung98** [comment]
감사합니다 ~~^^
