### ISSUE TITLE
5.12 File I/O & 함수보완

### ISSUE THREAD

**Issue by sungyi98** [hasung98/2021OSSL_Team3#13]

**Comment by sungyi98** [comment]
file I/O 함수 잘 돌아가는거 확인했습니다!!

**Comment by sungyi98** [comment]
createPlan함수와 updatePlan함수에서 년, 월, 일 입력시 int가 아닌 문자를 잘못 입력하면 무한루프가 돌아가는 error를 수정하기 위해서
char buff[100]을 추가하여 입력받은 값이 int인지 확인 후, int가 아니면 다시 입력받고 int이면 buff를 int로 바꾸어 저장해주는 기능을 추가하였습니다!

buff에 임시로 저장된 값은 check_char함수에 input으로 입력되는데, 이 함수에서는 buff내의 글자 하나하나를 확인하여 char가 하나라도 있으면 1을 return하고, 전부 int이면 0을 return 합니다. 
check_char가 1이면, 함수에서는 값을 다시 입력받습니다

**Comment by sungyi98** [comment]
selectMenu()에서 처음 메뉴값을 입력받을 때 char라 \n이 입력되지 않을까 해서 다른 함수들처럼 clearbuffer를 넣어주었는데, 처음 수행시에 buffer에 아무것도 없다보니 clearbuffer에서 무언가 값을 넣어주어야지 작동이 되는 오류가 발생하였습니다
그래서 이 부분에서는 clearbuffer()를 일단 주석처리 해두었는데, 혹시나 함수를 계속 작동하는 중에 selectMenu에서 무한루프 또는 입력을 하지 않았는데 (버퍼에 남아있던)값이 입력되는 현상이 나타난다면 그때 해결방법을 찾아보도록 해요!!

**Comment by hasung98** [comment]
아 !! clearbufffer에 그런 오류가 있었군요 감사합니다.

**Comment by hasung98** [comment]
메인 함수를 간소화 하자는 의견에 따라서 helpCalendar 함수로 간소화 시켰습니다 !

**Comment by sungyi98** [comment]
감사합니다!!:)
