### ISSUE TITLE
5.4 CRUD 함수 개발 

### ISSUE THREAD

**Issue by hasung98** [hasung98/2021OSSL_Team3#4]

**Comment by sungyi98** [comment]
함수 이름을 ~~Calendar보다 ~~Plan으로 하는게 어떨까요?

**Comment by hasung98** [comment]
아 그게 좋겠네요!

**Comment by sungyi98** [comment]
제가 수정 하겠습니다!!

**Comment by sungyi98** [comment]
그리고, Calendar_main을 main으로 수정하였습니다!

**Comment by hasung98** [comment]
네 좋아요

**Comment by sungyi98** [comment]
함수 위치를 파악하기 쉽게 하기 위해서 헤더파일 함수 배치순서와 .c파일 함수 배치순서를 동일하게 해두었습니다!! 참고해주세요

**Comment by hasung98** [comment]
수정 감사드립니다 ^^

**Comment by sungyi98** [comment]
type을 string으로 입력받는 방식에서 int형태로 (1.시험 2.과제 3.팀플)로 입력받는 방식으로 변경하였습니다

**Comment by sungyi98** [comment]
readPlan()함수를 보시면, 정보를 출력해서 보여줄 때에는 "type"을 값에따라서 1,2,3을 각각 "시험","과제","팀플"이라고 변경하여 출력해줄 수 있도록 구현하였습니다
