### ISSUE TITLE
5.5 CRUD함수 보완

### ISSUE THREAD

**Issue by sungyi98** [hasung98/2021OSSL_Team3#6]

**Comment by hasung98** [comment]
showCalendar함수 추가 했어요 !!

**Comment by sungyi98** [comment]
네 감사합니다:)

**Comment by sungyi98** [comment]
함수들 관련하여 간단한 설명 첨부합니다

**Comment by sungyi98** [comment]
Calendar.c 안의 함수에 관하여 간단한 설명

- p->type은 int형(1.시험 2.과제 3.팀플)으로 저장됨
- readPlan은 Calendar p 에 저장된 정보들(year, month, day, type, subject)를 읽어서 한줄로 나타내는데, 이때 int형으로 저장되어있는 type은 char형으로 표시됨
- int형으로 저장된 "type"을 문자로 변환하기 위해 사용되는 함수가 transer함수
- transer함수는 int형의 "type"을 파라미터(1,2,3)을 입력받아서 char형(시험, 과제, 팀플)으로 변환함

**Comment by sungyi98** [comment]
- transer함수 내부에는 char *p_type의 메모리가 allocation되어있고, 이 함수는 char type의 pointer를 반환형으로 함
- transer함수 내부에 allocation되어있는 메모리는 transer함수를 호출하는 함수들(searchPlan_type, readPlan)에서 free됨
- searchPlan_type함수와 readPlan함수는 transer로부터 받은 char형 포인터를 (char형태의 "type"값을 저장하는 char를 가리키는 포인터) p_type이라는 변수에 저장하고 출력한 후 char pointer의 메모리를 free함

**Comment by sungyi98** [comment]
- 프로그램을 시작하여 메뉴5번을 누르면, main에서 검색방법을 입력받음(1. 분류로 검색 2. 날짜로 검색)
- 1번을 입력시 searchPlan_type함수를 부르고, 2번을 입력시 searchPlan_month함수를 부름

[searchPlan_type 함수]
- searchPlan_type함수는 검색을 원하는 분류(1.시험 2.과제 3.팀플)을 입력받아 해당 분류의 일정을 모두 출력함
- 일정이 없으면, 해당 type의 일정이 없다고 출력함(ex. 과제 일정이 없습니다)
- 추가적으로, createPlan에서 type을 입력할 때 1,2,3 이외의 값을 입력하면 transer에서 "기타"로 분류되어 표시됨

**Comment by sungyi98** [comment]
[searchPlan_month 함수]
- 검색방법을 입력받음(1. 월로 검색 2.월&일로 검색 0.종료), 이외의 숫자 입력시 다시 입력받음 
- 월로 검색시 해당 월의 일정을 전부 표시하고, 월과 일로 검색시 해당 날짜의 일정을 모두 표시함

**Comment by sungyi98** [comment]
추가적으로 보완할 기능: 
- 월/월&일로 검색시 12월을 넘으면 error표시, 31일을 넘으면 error표시
- type에 기타 항목을 추가로 만들 계획, 기타 항목으로 입력시 분류를 직접 입력할 수 있는 기능 구상중
- type으로 검색시 0,1,2,3이외의 숫자 입력시 error표시 및 다시 입력받기
