### ISSUE TITLE
5.6 git clone시 한글출력 오류 

### ISSUE THREAD

**Issue by hasung98** [hasung98/2021OSSL_Team3#9]

**Comment by hasung98** [comment]
![image](https://user-images.githubusercontent.com/75055715/117239228-5bcea300-ae69-11eb-8f0b-b63ff575020a.png)

알려주신 방법대로 진행하고 설정해서 한글들어간 파일 다시 commit 했습니다! 
제 컴퓨터에서는 다 지우고 clone하니 이제 한글 깨짐 오류가 안뜨네요!!
학우님 컴퓨터에서 확인해주시면 감사하겠습니다 ^^ !!

**Comment by hasung98** [comment]
그리고 gitignore파일 만들었습니다

**Comment by sungyi98** [comment]
네 감사합니다!!:-)

**Comment by sungyi98** [comment]
한글깨짐현상이 나타난다면 ,터미널에 
set LC_ALL=ko_KR.UTF-8 를 입력한 후에 다시 make는 방법을 사용해보세요!

**Comment by hasung98** [comment]
감사해요
